name: Publish to NPMjs

on:
  push:
    tags:
      - "v[0-9]*.[0-9]*.[0-9]*"

jobs:
  build-and-check-and-publish:
    runs-on: ubuntu-latest

    environment: npmjs
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v7

      - name: Set up Node
        uses: actions/setup-node@v7
        with:
          node-version: "25.x"
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false

      - name: Install using lockfile
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Test package types
        run: npx -y @arethetypeswrong/cli --pack .

      - name: Run tests
        run: npm test

      - name: Publish to NPMjs
        run: npm publish --provenance --access public

      - name: Upload built package
        uses: actions/upload-artifact@v7
        with:
          name: Package
          path: dist
